title: "Kagan Bağdemir"
description: "Maschinenbau (ITPL) · Data & Logistics · Werkstudent / Praktikum / Junior"
url: "https://kaganbagdemir.de"
baseurl: ""
permalink: /blog/:title/
markdown: kramdown

# SEO için
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Sosyal/künye
author:
  name: "Kagan Bağdemir"
social:
  links:
    - "https://github.com/kahnri"
    - "https://www.linkedin.com/in/..."   # gerçek URL’ni ekle
    - "mailto:hi@kaganbagdemir.de"
